language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install --no-interaction

before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

script:
  - composer validate --strict
  - php phpcs.phar --standard=php_cs.xml src/
  - vendor/bin/phpunit tests/unit/
  - php phpat phpat.yml
  - php phpat tests/functional/functional.yaml
