name: release-phar

on:
  release:
    types: [published, prereleased]

jobs:
  release-phar:
    name: Build and upload Phar
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1
      
      - name: Install PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          tools: composer
          ini-values: phar.readonly=Off
      
      - name: Install dependencies
        run: composer install
      
      - name: Build archive
        run: php build.php 
      
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/phpat.phar application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
